/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;


import Daos.billDao;
import Daos.billDrinkDao;
import Daos.buyDao;
import Daos.drinkDao;
import entities.Bill;
import entities.Buy;
import entities.Drink;
import entities.billDrink;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Date;
import playstation.loginFrame;
/**
 *
 * @author SaSa
 */
public class inventoryFrameAdmin extends javax.swing.JFrame {

    /**
     * Creates new form costFrame
     */
    public inventoryFrameAdmin() {
        initComponents();
        this.setTitle("Playstation");
        Toolkit tk = Toolkit.getDefaultToolkit();
        this.setSize(tk.getScreenSize().width,tk.getScreenSize().width);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        billTable = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        buyTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        totalDrinks = new javax.swing.JLabel();
        totalBuy = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        totalPlayStation = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jDateChooserTo = new com.toedter.calendar.JDateChooser();
        jDateChooserFrom = new com.toedter.calendar.JDateChooser();
        totalDrinks1 = new javax.swing.JLabel();
        totalDrinks2 = new javax.swing.JLabel();
        totalDrinks3 = new javax.swing.JLabel();
        totalDrinks4 = new javax.swing.JLabel();
        totalBuy1 = new javax.swing.JLabel();
        total1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu21 = new javax.swing.JMenu();
        jMenu22 = new javax.swing.JMenu();
        jMenu23 = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        billTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        billTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الاجمالى", "سعر ", "العدد", "الاسم"
            }
        ));
        billTable.setRowHeight(25);
        billTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(billTable);

        buyTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "الوقت", "التاريخ", "سعر ", "الاسم", "رقم"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        buyTable.setRowHeight(25);
        buyTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(buyTable);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("المشتريات");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("المبيعات");

        totalDrinks.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totalDrinks.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        totalBuy.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totalBuy.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        total.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("جرد");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        totalPlayStation.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totalPlayStation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("عودة");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        totalDrinks1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totalDrinks1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalDrinks1.setText("الى");

        totalDrinks2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totalDrinks2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalDrinks2.setText("من");

        totalDrinks3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totalDrinks3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalDrinks3.setText("بلاي استيشن :");

        totalDrinks4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totalDrinks4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalDrinks4.setText("مشاريب :");

        totalBuy1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        totalBuy1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalBuy1.setText("مشتريات :");

        total1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        total1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        total1.setText("الاجمالى :");

        jMenu3.setText("فواتير");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu3.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu3);

        jMenu4.setText("مشتريات");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu4.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu4);

        jMenu5.setText("مشاريب");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu5.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu5);

        jMenu6.setText("المخزن");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu6.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu6);

        jMenu21.setText("الاجهزه");
        jMenu21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu21.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jMenu21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu21MouseClicked(evt);
            }
        });
        jMenu21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu21ActionPerformed(evt);
            }
        });
        jMenuBar2.add(jMenu21);

        jMenu22.setText("المستخدمين");
        jMenu22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu22.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jMenu22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu22MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu22);

        jMenu23.setText("تسجيل خروج");
        jMenu23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu23.setMargin(new java.awt.Insets(5, 5, 5, 5));
        jMenu23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu23MouseClicked(evt);
            }
        });
        jMenuBar2.add(jMenu23);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(total1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(totalBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalBuy1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(totalPlayStation, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(totalDrinks3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalDrinks, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalDrinks4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(287, 287, 287)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDateChooserTo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(totalDrinks1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooserFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalDrinks2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jDateChooserFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserTo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalDrinks2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalDrinks1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalPlayStation, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalDrinks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalDrinks3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalBuy, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalDrinks4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(totalBuy1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tableActionBuy();
        tableActionDrinks();
        total.setText(Double.toString(((Double.parseDouble(totalDrinks.getText())) + (Double.parseDouble(totalPlayStation.getText())) - (Double.parseDouble(totalBuy.getText())))));
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void buyTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buyTableMouseClicked

    private void billTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billTableMouseClicked
            
        // TODO add your handling code here:
    }//GEN-LAST:event_billTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tableActionBuyDate();
        tableActionDrinksDate();
        total.setText(Double.toString(((Double.parseDouble(totalDrinks.getText())) + (Double.parseDouble(totalPlayStation.getText())) - (Double.parseDouble(totalBuy.getText())))));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jDateChooserTo.setDateFormatString("");
        jDateChooserFrom.setDateFormatString("");
        tableActionBuy();
        tableActionDrinks();
        total.setText(Double.toString(((Double.parseDouble(totalDrinks.getText())) + (Double.parseDouble(totalPlayStation.getText())) - (Double.parseDouble(totalBuy.getText())))));
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        billFrameAdmin bfa = new billFrameAdmin();
        bfa.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        buyFrameAdmin bfa = new buyFrameAdmin();
        bfa.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        drinkFrameAdmin dfa = new drinkFrameAdmin();
        dfa.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        inventoryFrameAdmin bfa = new inventoryFrameAdmin();
        bfa.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenu21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu21MouseClicked

        deviceFrameAdmin d=new deviceFrameAdmin();
        d.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu21MouseClicked

    private void jMenu21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu21ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jMenu21ActionPerformed

    private void jMenu22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu22MouseClicked
        // TODO add your handling code here:
        usersFrameAdmin u=new usersFrameAdmin();
        u.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu22MouseClicked

    private void jMenu23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu23MouseClicked
        // TODO add your handling code here:
        loginFrame lg = new loginFrame();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu23MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inventoryFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inventoryFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inventoryFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inventoryFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inventoryFrameAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable billTable;
    private javax.swing.JTable buyTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooserFrom;
    private com.toedter.calendar.JDateChooser jDateChooserTo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel total;
    private javax.swing.JLabel total1;
    private javax.swing.JLabel totalBuy;
    private javax.swing.JLabel totalBuy1;
    private javax.swing.JLabel totalDrinks;
    private javax.swing.JLabel totalDrinks1;
    private javax.swing.JLabel totalDrinks2;
    private javax.swing.JLabel totalDrinks3;
    private javax.swing.JLabel totalDrinks4;
    private javax.swing.JLabel totalPlayStation;
    // End of variables declaration//GEN-END:variables
public void tableAction()
    {
        DefaultTableModel model = (DefaultTableModel) billTable.getModel();
        model.setRowCount(0);
        billDao dd = new billDao();
        List<Bill>dr=dd.selectBill();
        model =(DefaultTableModel) billTable.getModel();
        Object[] row = new Object[3];
        for (int i = 0; i < dr.size(); i++) 
        {
         row[0]=dr.get(i).getBillId();
         row[1]=dr.get(i).getBillPrice();
         model.addRow(row);
        }
        List<Bill> b = dd.sumBill();
        for(int i=0;i<b.size();i++)
        {
            totalPlayStation.setText(b.get(i).getBillId()+"");
        }
        }

public void tableActionDrinks()
    {
        DefaultTableModel model = (DefaultTableModel) billTable.getModel();
        model.setRowCount(0);
        billDao billd = new billDao();
        drinkDao dd = new drinkDao();
        billDrinkDao bdd = new billDrinkDao();
        List<Drink>dr=dd.selectDrink();
        model =(DefaultTableModel) billTable.getModel();
        if(dr.size()>0)
        {
        Object[] row = new Object[4];
        for (int i = 0; i < dr.size(); i++) 
        {
         int count = 0;
         List<billDrink> bd = bdd.countBillDrink(dr.get(i).getDrinkId()+"");
         if(bd.size()>0)
         {
         for(int j=0;j<bd.size();j++)
         {
         if(bd.get(j).getBillDrinkID()>0)
         {
         count = bd.get(j).getBillDrinkID();
         row[3]=dr.get(i).getDrinkName();
         row[2]=bd.get(j).getBillDrinkID();             
         row[1]=dr.get(i).getDrinkPrice();
         row[0]=Double.parseDouble(dr.get(i).getDrinkPrice()) * count;
         model.addRow(row);
         }
         }
         
        }
        }
        List<billDrink> bd = bdd.sumBillDrink();
        for(int i=0;i<bd.size();i++)
        {
            totalDrinks.setText(bd.get(i).getBillDrinkID()+"");
        }
        List<Bill> b = billd.sumBill();
        for(int i=0;i<b.size();i++)
        {
            totalPlayStation.setText(b.get(i).getBillPrice());
        }
        }
        }

public void tableActionBuy()
    {
        DefaultTableModel model = (DefaultTableModel) buyTable.getModel();
        model.setRowCount(0);
        buyDao bd = new buyDao();
        List<Buy>buy=bd.selectBuy();
        model =(DefaultTableModel) buyTable.getModel();
        Object[] row = new Object[5];
        for (int i = 0; i < buy.size(); i++) 
        {
         row[0]=buy.get(i).getBuyTime();
         row[1]=buy.get(i).getBuyDate();
         row[2]=Double.parseDouble(buy.get(i).getBuyPrice());
         row[3]=buy.get(i).getBuyName();
         row[4]=buy.get(i).getBuyId();
         model.addRow(row);
        }
        List<Buy> b = bd.sumBuy();
        for(int i=0;i<b.size();i++)
        {
            totalBuy.setText(b.get(i).getBuyId()+"");
        }
        
    }

public void tableActionDrinksDate()
    {
        DefaultTableModel model = (DefaultTableModel) billTable.getModel();
        model.setRowCount(0);
        Date to = jDateChooserTo.getDate();
        Date from = jDateChooserFrom.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String fromStr = sdf.format(from);
        String toStr = sdf.format(to);
        billDao billd = new billDao();
        drinkDao dd = new drinkDao();
        billDrinkDao bdd = new billDrinkDao();
        List<Drink>dr=dd.selectDrink();
        model =(DefaultTableModel) billTable.getModel();
        if(dr.size()>0)
        {
        Object[] row = new Object[4];
        for (int i = 0; i < dr.size(); i++) 
        {
         int count = 0;
         List<billDrink> bd = bdd.countBillDrinkDate(fromStr,toStr,dr.get(i).getDrinkId()+"");
         if(bd.size()>0)
         {
         row[3]=dr.get(i).getDrinkName();
         for(int j=0;j<bd.size();j++)
         {
         count = bd.get(j).getBillDrinkID();
         row[2]=bd.get(j).getBillDrinkID();             
         }
         row[1]=dr.get(i).getDrinkPrice();
         row[0]=Double.parseDouble(dr.get(i).getDrinkPrice()) * count;
         
         
         model.addRow(row);
        }
        }
        List<billDrink> bd = bdd.sumBillDrinkDate(fromStr, toStr);
        for(int i=0;i<bd.size();i++)
        {
            totalDrinks.setText(bd.get(i).getBillDrinkID()+"");
        }
        List<Bill> b = billd.sumBillDate(fromStr, toStr);
        for(int i=0;i<b.size();i++)
        {
            totalPlayStation.setText(b.get(i).getBillPrice());
        }
        
        }
        }

public void tableActionBuyDate()
    {
        DefaultTableModel model = (DefaultTableModel) buyTable.getModel();
        model.setRowCount(0);
        Date to = jDateChooserTo.getDate();
        Date from = jDateChooserFrom.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String toStr = sdf.format(to);
        String fromStr = sdf.format(from);
        buyDao bd = new buyDao();
        List<Buy>buy=bd.selectBuyDate(fromStr,toStr);
        model =(DefaultTableModel) buyTable.getModel();
        Object[] row = new Object[5];
        for (int i = 0; i < buy.size(); i++) 
        {
         row[0]=buy.get(i).getBuyTime();
         row[1]=buy.get(i).getBuyDate();
         row[2]=Double.parseDouble(buy.get(i).getBuyPrice());
         row[3]=buy.get(i).getBuyName();
         row[4]=buy.get(i).getBuyId();
         model.addRow(row);
         
        }
        List<Buy> b = bd.sumBuyDate(fromStr, toStr);
        for(int i=0;i<b.size();i++) 
        {
            totalBuy.setText(b.get(i).getBuyId()+"");
        }
        
    }

}

