/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package playstation;

import Frames.Room1;
import Frames.Room2;
import Frames.Room3;
import Frames.Room4;
import Frames.Room5;
import Frames.Room6;
import Frames.Room62;
import Frames.Room7;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JPanel;

/**
 *
 * @author Mostafa
 */
public class mainFrame extends javax.swing.JFrame {

    Room1 r1 = new Room1();
    Room2 r2 = new Room2();
    Room3 r3 = new Room3();
    Room4 r4 = new Room4();
    Room5 r5 = new Room5();
    Room6 r6 = new Room6(); 
    Room62 r62 = new Room62();
    Room7 r7 = new Room7();
    
        
    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
    initComponents();
    Toolkit tk = Toolkit.getDefaultToolkit();
    this.setSize(tk.getScreenSize().width,tk.getScreenSize().width);
    Proom1.add(r1.getContentPane());
    Proom2.add(r2.getContentPane());
    Proom3.add(r3.getContentPane());
    Proom4.add(r4.getContentPane());
    Proom5.add(r5.getContentPane());
    Proom6.add(r6.getContentPane());   
    Proom9.add(r62.getContentPane());
    Proom7.add(r7.getContentPane());

    Proom1.setVisible(true);
    Proom2.setVisible(false);
    Proom3.setVisible(false);
    Proom4.setVisible(false);
    Proom5.setVisible(false);
    Proom6.setVisible(false);
    Proom9.setVisible(false);
    Proom7.setVisible(false);
        }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Room4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Proom5 = new javax.swing.JPanel();
        Proom2 = new javax.swing.JPanel();
        Proom4 = new javax.swing.JPanel();
        Proom1 = new javax.swing.JPanel();
        Proom6 = new javax.swing.JPanel();
        Proom3 = new javax.swing.JPanel();
        Proom9 = new javax.swing.JPanel();
        Proom7 = new javax.swing.JPanel();
        btnAdmin = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Room1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Room3");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Room2");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Room5");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        Room4.setText("Room4");
        Room4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Room4ActionPerformed(evt);
            }
        });

        jButton6.setText("Room7");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Room6(1)");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(788, 800));
        jLayeredPane1.setLayout(new javax.swing.OverlayLayout(jLayeredPane1));

        Proom5.setPreferredSize(new java.awt.Dimension(788, 800));

        javax.swing.GroupLayout Proom5Layout = new javax.swing.GroupLayout(Proom5);
        Proom5.setLayout(Proom5Layout);
        Proom5Layout.setHorizontalGroup(
            Proom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );
        Proom5Layout.setVerticalGroup(
            Proom5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Proom5);

        Proom2.setPreferredSize(new java.awt.Dimension(788, 1048));

        javax.swing.GroupLayout Proom2Layout = new javax.swing.GroupLayout(Proom2);
        Proom2.setLayout(Proom2Layout);
        Proom2Layout.setHorizontalGroup(
            Proom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Proom2Layout.setVerticalGroup(
            Proom2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Proom2);

        Proom4.setPreferredSize(new java.awt.Dimension(788, 1048));

        javax.swing.GroupLayout Proom4Layout = new javax.swing.GroupLayout(Proom4);
        Proom4.setLayout(Proom4Layout);
        Proom4Layout.setHorizontalGroup(
            Proom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Proom4Layout.setVerticalGroup(
            Proom4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Proom4);

        Proom1.setPreferredSize(new java.awt.Dimension(788, 1048));

        javax.swing.GroupLayout Proom1Layout = new javax.swing.GroupLayout(Proom1);
        Proom1.setLayout(Proom1Layout);
        Proom1Layout.setHorizontalGroup(
            Proom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Proom1Layout.setVerticalGroup(
            Proom1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Proom1);

        Proom6.setPreferredSize(new java.awt.Dimension(788, 1048));

        javax.swing.GroupLayout Proom6Layout = new javax.swing.GroupLayout(Proom6);
        Proom6.setLayout(Proom6Layout);
        Proom6Layout.setHorizontalGroup(
            Proom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Proom6Layout.setVerticalGroup(
            Proom6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Proom6);

        Proom3.setPreferredSize(new java.awt.Dimension(788, 1048));

        javax.swing.GroupLayout Proom3Layout = new javax.swing.GroupLayout(Proom3);
        Proom3.setLayout(Proom3Layout);
        Proom3Layout.setHorizontalGroup(
            Proom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        Proom3Layout.setVerticalGroup(
            Proom3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Proom3);

        Proom9.setPreferredSize(new java.awt.Dimension(788, 800));

        javax.swing.GroupLayout Proom9Layout = new javax.swing.GroupLayout(Proom9);
        Proom9.setLayout(Proom9Layout);
        Proom9Layout.setHorizontalGroup(
            Proom9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );
        Proom9Layout.setVerticalGroup(
            Proom9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Proom9);

        Proom7.setPreferredSize(new java.awt.Dimension(788, 800));

        javax.swing.GroupLayout Proom7Layout = new javax.swing.GroupLayout(Proom7);
        Proom7.setLayout(Proom7Layout);
        Proom7Layout.setHorizontalGroup(
            Proom7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
        );
        Proom7Layout.setVerticalGroup(
            Proom7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        jLayeredPane1.add(Proom7);

        btnAdmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAdmin.setText("Admin");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        jButton8.setText("Room6(2)");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1018, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Room4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Room4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Proom1.setVisible(true);
    Proom2.setVisible(false);
    Proom3.setVisible(false);
    Proom4.setVisible(false);
    Proom5.setVisible(false);
    Proom6.setVisible(false);
     Proom9.setVisible(false);
    Proom7.setVisible(false);
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    Proom1.setVisible(false);
    Proom2.setVisible(true);
    Proom3.setVisible(false);
    Proom4.setVisible(false);
    Proom5.setVisible(false);
    Proom6.setVisible(false);
     Proom9.setVisible(false);
    Proom7.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Room4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Room4ActionPerformed
Proom1.setVisible(false);
    Proom2.setVisible(false);
    Proom3.setVisible(false);
    Proom4.setVisible(true);
    Proom5.setVisible(false);
    Proom6.setVisible(false);
     Proom9.setVisible(false);
    Proom7.setVisible(false);
            // TODO add your handling code here:
    }//GEN-LAST:event_Room4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    Proom1.setVisible(false);
    Proom2.setVisible(false);
    Proom3.setVisible(true);
    Proom4.setVisible(false);
    Proom5.setVisible(false);
    Proom6.setVisible(false);
     Proom9.setVisible(false);
    Proom7.setVisible(false);
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
Proom1.setVisible(false);
    Proom2.setVisible(false);
    Proom3.setVisible(false);
    Proom4.setVisible(false);
    Proom5.setVisible(true);
    Proom6.setVisible(false);
     Proom9.setVisible(false);
    Proom7.setVisible(false);
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
Proom1.setVisible(false);
    Proom2.setVisible(false);
    Proom3.setVisible(false);
    Proom4.setVisible(false);
    Proom5.setVisible(false);
    Proom6.setVisible(true);
     Proom9.setVisible(false);
    Proom7.setVisible(false);
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
Proom1.setVisible(false);
    Proom2.setVisible(false);
    Proom3.setVisible(false);
    Proom4.setVisible(false);
    Proom5.setVisible(false);
    Proom6.setVisible(false);
     Proom9.setVisible(false);
    Proom7.setVisible(true);
            // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
        loginFrame l=new loginFrame();
        l.setVisible(true);
    }//GEN-LAST:event_btnAdminActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    Proom9.setVisible(true);  
    Proom1.setVisible(false);
    Proom2.setVisible(false);
    Proom3.setVisible(false);
    Proom4.setVisible(false);
    Proom5.setVisible(false);
    Proom6.setVisible(false);
    Proom7.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Proom1;
    private javax.swing.JPanel Proom2;
    private javax.swing.JPanel Proom3;
    private javax.swing.JPanel Proom4;
    private javax.swing.JPanel Proom5;
    private javax.swing.JPanel Proom6;
    private javax.swing.JPanel Proom7;
    private javax.swing.JPanel Proom9;
    private javax.swing.JButton Room4;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
